name: Generate Sponsors list
on:
  workflow_dispatch:
  schedule:
    - cron: '31 6 * * *'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v5

      - name: Generate Sponsors üíñ
        uses: JamesIves/github-sponsors-readme-action@v1.5.6
        with:
          token: ${{ secrets.SOFIIA_SPONSORS_READ_TOKEN }}
          file: 'README.md'
          active-only: false
          include-private: true

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          
          # Check if there are any staged changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          
          git commit -m "Update list of sponsors"
          git push origin master
